name: Push to Hugging Face hub
on:
  push:
    branches: [main]
    paths: 
      - '.github/workflows/hf_space.yml'
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Prepare and push to HF
        run: |

          uv sync -U
          uv export --no-hashes --no-emit-project > requirements.txt

          # Prepare space
          mkdir $SPACE_NAME
          cd $SPACE_NAME
          cp -f ../requirements.txt .
          cp -f ../src/infer.py app.py
          cp -f ../example1.wav .
          cp -f ../.github/Dockerfile.hf_space Dockerfile

          # Prepare README
          cat > README.md <<EOL
          ---
          title: Transcribe Hebrew Speech into IPA
          emoji: ðŸŽ™ï¸
          colorFrom: red
          colorTo: blue
          sdk: docker
          sdk_version: "5.45.0"
          app_file: app.py
          pinned: false
          ---
          EOL

          # Git
          git lfs install
          rm -rf .git
          rm -rf .gitignore

          git init
          git lfs track "*.wav"
          git branch -M main
          git config --global user.email "thewh1teagle"
          git config --global user.name "thewh1teagle"
          git remote add origin https://$HF_USERNAME:$HF_TOKEN@huggingface.co/spaces/$HF_USERNAME/$SPACE_NAME

          git add .
          git commit -m "latest"
          git push --force origin main
          

        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_USERNAME: "thewh1teagle"
          SPACE_NAME: "whisper-heb-nikud"